### PR TITLE
Update to support multi-targeting

### PR DESCRIPTION
**Pull request by conradmicallef**
The update essentially creates a multi-targeted version of the library
Essentially only project files were modified and only 1 cs file was modified as the named properties are now in new project files.

Kindly consider for inclusion into your mainstream branch

the main advantages is that this essentially makes your library ready for .net core

### CODE REVIEW

**Comment by kbilsted** [comment]
Hi Conrad

Many thanks. At the moment the release to nuget is controlled by `DeployToNuget.cmd` I would think we need to do changes there as well. Is that something you can help with? Or maybe a different release process is in order?

**Comment by kbilsted** [comment]
your code doesn't build.

**Comment by kbilsted** [comment]
I've upgraded to v.4.6.1 now

**Comment by kbilsted** [comment]
if you dont  know how to do branching we can do a short screen share session and i can show you

**Comment by conradmicallef** [comment]
Its ok – do you need me to do a branch with my changes ? or you mean for the future ?

Sent from Mail for Windows 10

**Comment by kbilsted** [comment]
All PR. Including this one. If you pull from my master and start over.

**Pull request closed without merging**
