### PR TITLE
Added caching for the configuration

### PR DESCRIPTION
**Pull request by harrybellamy**
Added caching for the configuration in a generic class (see issue #37).

### CODE REVIEW

**Comment by kbilsted** [comment]
Many Thanks for the PR. 

There are a few things I think need a bit of tweaking if you don't mind.

0. Too many new namespaces - it doesn't follow the current style of the code
1. the use of `#region` - it doesn't follow the current style of the code
2. a `get()` that mutates state 
3. an interface abstraction for coincidental method name

**Comment by harrybellamy** [comment]
I've updated the PR based off your suggestions - removed the new classes and added new logic to `Configuration.cs`.
I have spotted a potential bug though that was already present for the converter lookup implementation - if a `ValueConverter` is looked up for a type then a new one is added for the same type, the first implementation will still be returned from `TryGetValueConverter`.

I can look at fixing this in this PR if desired.

**Comment by kbilsted** [comment]
Hi thanks for reporting.

I was thinking, the bug scenario fix is just as bad as the bug? Since for the type `T` at some point one converter is used, then later, another converter is used without any warning or transparency.

**Comment by kbilsted** [comment]
regarding the cache class, try using a func as parameter for the ctor rather than a common interface. Perhaps in a new branch so as not to keep too much clutter around.

**Comment by harrybellamy** [comment]
I've backed out the cache class and replaced with a simple dictionary lookup in `Configration.cs`.

**Comment by harrybellamy** [comment]
Closing as I should've branched from master for this.

**Pull request closed without merging**
